# Generated by Django 3.2.7 on 2026-01-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyes', '0003_doctortbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortbl',
            name='image',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
