# Generated by Django 3.2.7 on 2026-03-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyes', '0011_appointment_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_file',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
