# Generated by Django 3.2.7 on 2026-03-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalyes', '0012_prescription_prescription_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='location',
            field=models.CharField(default='Clinic', max_length=150),
        ),
    ]
